version: '3'

services:
  carteleramvc:
    image: carteleramvc:dev
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - NUGET_PACKAGES=C:\.nuget\packages
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_carteleramvc$
    volumes:
      - C:\Users\xCrixus\source\repos\NetCore + MVC app\CarteleraMvc\CarteleraMvc:C:\app
      - C:\Users\xCrixus\onecoremsvsmon\15.0.27130.2024:C:\remote_debugger:ro
#$nuget_volume_mapping_carteleramvc$
    entrypoint: C:\\remote_debugger\\x64\\msvsmon.exe /noauth /anyuser /silent /nostatus /noclrwarn /nosecuritywarn /nofirewallwarn /nowowwarn /timeout:2147483646
    labels:
      com.microsoft.visualstudio.debuggee.program: "\"C:\\Program Files\\dotnet\\dotnet.exe\""
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_carteleramvc$ bin\\Debug\\netcoreapp2.1\\CarteleraMvc.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "C:\\app"
      com.microsoft.visualstudio.debuggee.killprogram: "C:\\remote_debugger\\x64\\utils\\KillProcess.exe dotnet.exe"
